// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwBwM4uktZ2aMCgdXkatrHJ9qbI7TZsmU',
    appId: '1:528858367803:web:1fdbbb344db98f2b84591e',
    messagingSenderId: '528858367803',
    projectId: 'cau-safebite',
    authDomain: 'cau-safebite.firebaseapp.com',
    storageBucket: 'cau-safebite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0ujByh2sJLPDKSHprPH4VIIi_Upav7k',
    appId: '1:528858367803:android:b18290b908d8aa2584591e',
    messagingSenderId: '528858367803',
    projectId: 'cau-safebite',
    storageBucket: 'cau-safebite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfM45REJMk-E0uW1E6_GDo4f6iGnsqQQ',
    appId: '1:528858367803:ios:fc5edcb9c1e3b6d084591e',
    messagingSenderId: '528858367803',
    projectId: 'cau-safebite',
    storageBucket: 'cau-safebite.firebasestorage.app',
    iosBundleId: 'com.example.cauSafebite',
  );
}
